pub mod channel;
pub use channel::ColorChannel;
pub mod colorerror;
pub use colorerror::ColorError;
pub mod hex;
pub use hex::ToHex;
pub mod primary;
pub use primary::{Primary, PrimaryColor};
pub mod rgba;
pub use rgba::RGBA;
