name: CI

on:
  push:
    branches: [ "odin" ]
  pull_request:
    branches: [ "odin" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
